from app import app
from auto_discovery import register_auto_discovery
from bulk_actions import register_bulk_actions
from collection_dashboard import register_collection_dashboard
from discovery_pipeline import register_discovery_pipeline
from follow_up import register_follow_up
from follow_up_draft import register_follow_up_draft
from miyagi_enrichment import register_miyagi_enrichment
from operator_enrichment import register_operator_enrichment
from regional_sources import register_regional_sources
from sales_action import register_sales_action
from sales_activity import register_sales_activity
from sales_analytics import register_sales_analytics
from sales_priority import register_sales_priority
from security_hardening import register_security_hardening
from sendai_official import register_sendai_official
from system_tools import register_system_tools
from target_finder import register_target_finder
from today_dashboard import register_today_dashboard

register_bulk_actions(app)
register_miyagi_enrichment(app)
register_regional_sources(app)
register_collection_dashboard(app)
register_sales_priority(app)
register_sales_action(app)
register_sales_activity(app)
register_sales_analytics(app)
register_follow_up(app)
register_follow_up_draft(app)
register_today_dashboard(app)
register_system_tools(app)
register_auto_discovery(app)
register_operator_enrichment(app)
register_discovery_pipeline(app)
register_target_finder(app)
register_sendai_official(app)
register_security_hardening(app)
